// Generated by CoffeeScript 1.3.3
(function() {
  var bind_listeners, initialize, old_round, places;

  places = [
    {
      name: '新竹市立體育場',
      url: 'http://g.co/maps/xk525'
    }, {
      name: '新竹巨城購物中心7樓溜冰場旁',
      url: 'http://goo.gl/maps/0AmZO'
    }
  ];

  old_round = '';

  initialize = function() {
    var p, _i, _len;
    for (_i = 0, _len = places.length; _i < _len; _i++) {
      p = places[_i];
      $('select#place').prepend("<option>" + p.name + "</option>");
      $('input#place_url').val(p.url);
    }
    old_round = $('#round').val();
    $('#round').closest('.controls').find('span').hide();
    return $('#datepicker').closest('.controls').find('span').hide();
  };

  bind_listeners = function() {
    $('select#place').change(function() {
      var p, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = places.length; _i < _len; _i++) {
        p = places[_i];
        if ($('select#place').val() === p.name) {
          $('input#place_url').val(p.url);
          break;
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
    return $('#submit').click(function() {
      var flag;
      flag = true;
      if ($('#round').val() === old_round) {
        $('#round').closest('.controls').find('span').show();
        $('#round').closest('.control-group').addClass('error');
        flag = false;
      }
      if ($('#datepicker').val() === '') {
        $('#datepicker').closest('.controls').find('span').show();
        $('#datepicker').closest('.control-group').addClass('error');
        flag = false;
      }
      $('#round').on('keyup', function() {
        $('#round').closest('.controls').find('span').hide();
        return $('#round').closest('.control-group').removeClass('error');
      });
      $('#datepicker').on('keyup change', function() {
        $('#datepicker').closest('.controls').find('span').hide();
        return $('#datepicker').closest('.control-group').removeClass('error');
      });
      if (flag) {
        return $('form').submit();
      }
    });
  };

  $(function() {
    initialize();
    return bind_listeners();
  });

}).call(this);
