// Generated by CoffeeScript 1.3.3
var bind_listeners, initialize, old_round, places;

places = [
  {
    name: '新竹市立體育場',
    url: 'http://g.co/maps/xk525'
  }, {
    name: '新竹巨城購物中心7樓溜冰場旁',
    url: 'http://goo.gl/maps/0AmZO'
  }
];

old_round = '';

initialize = function() {
  var p, _i, _len;
  $('#datepicker').datepicker();
  for (_i = 0, _len = places.length; _i < _len; _i++) {
    p = places[_i];
    $('select#place').prepend("<option>" + p.name + "</option>");
    $('input#place_url').val(p.url);
  }
  old_round = $('#round').val();
  $('#round ~ span').hide();
  return $('#datepicker ~ span').hide();
};

bind_listeners = function() {
  $('select#place').change(function() {
    var p, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = places.length; _i < _len; _i++) {
      p = places[_i];
      if ($('select#place').val() === p.name) {
        $('input#place_url').val(p.url);
        break;
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  });
  return $('#submit').click(function() {
    var flag;
    flag = true;
    if ($('#round').val() === old_round) {
      $('#round ~ span').show();
      $('#round ~ span').parent().parent().addClass('error');
      flag = false;
    }
    if ($('#datepicker').val() === '') {
      $('#datepicker ~ span').show();
      $('#datepicker ~ span').parent().parent().addClass('error');
      flag = false;
    }
    $('#round').change(function() {
      $('#round ~ span').hide();
      return $('#round ~ span').parent().parent().removeClass('error');
    });
    $('#datepicker').change(function() {
      $('#datepicker ~ span').hide();
      return $('#datepicker ~ span').parent().parent().removeClass('error');
    });
    if (flag) {
      return $('form').submit();
    }
  });
};

$(function() {
  initialize();
  return bind_listeners();
});
