application: hiyahome
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img
  
- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  
- url: /admin711
  script: main.py
  login: required

- url: /set_date
  script: main.py
  login: required  

- url: /.*
  script: main.py

